### Get all meals
GET http://localhost:3000/meals HTTP/1.1

### Post a new meal
POST http://localhost:3000/meals HTTP/1.1
content-type: application/json

{
    "calories": 250,
    "cookTemp": "Med High",
    "cookTime": "15 Min",
    "directions": "Cook chicken. Cut chicken. Place on salad.",
    "ingredientAmounts": ["2", "4", "1/2", "1"],
    "ingredientUnits": ["Cup", "Cup", "Cup", "Cup"],
    "ingredients": ["Chicken Breast", "Romaine Lettuce", "Shredded Parmesan Cheese", "Croutons"],
    "mealName": "Chicken Ceasar Salad",
    "prepTime": "10 Min",
    "servings": 4
}


###Get all users
GET http://localhost:3000/ HTTP/1.1

### Post a new user
POST http://localhost:3000/ HTTP/1.1
content-type: application/json

{
    "username": "yoyo",
    "password": "number"
}

### Render get all meals
GET https://lesson-5-u9we.onrender.com/meals HTTP/1.1

### Render post new meal
POST https://lesson-5-u9we.onrender.com/meals HTTP/1.1
content-type: application/json

{
    "calories": 250,
    "cookTemp": "Med High",
    "cookTime": "15 Min",
    "directions": "Cook chicken. Cut chicken. Place on salad.",
    "ingredientAmounts": ["2", "4", "1/2", "1"],
    "ingredientUnits": ["Cup", "Cup", "Cup", "Cup"],
    "ingredients": ["Chicken Breast", "Romaine Lettuce", "Shredded Parmesan Cheese", "Croutons"],
    "mealName": "Chicken Ceasar Salad",
    "prepTime": "10 Min",
    "servings": 4
}

###Render get all users
GET https://lesson-5-u9we.onrender.com/ HTTP/1.1

### Render post a new user
POST https://lesson-5-u9we.onrender.com/ HTTP/1.1
content-type: application/json

{
    "username": "yoyo",
    "password": "number"
}