### Get all meals
GET http://localhost:3000/meals HTTP/1.1

### Get One Meal
GET http://localhost:3000/meals/Chicken%20Pizza HTTP/1.1

### Post a new meal
POST http://localhost:3000/meals HTTP/1.1
content-type: application/json

{
    "calories": 250,
    "cookTemp": "Med High",
    "cookTime": "15 Min",
    "directions": "Cut chicken. Place on salad.",
    "ingredientAmounts": ["2", "4", "1/2", "1"],
    "ingredientUnits": ["Cup", "Cup", "Cup", "Cup"],
    "ingredients":  ["Chicken Breast", "Romaine Lettuce", "Shredded Parmesan Cheese", "Croutons"],
    "mealName": "Chicken Ceasar Salad",
    "prepTime": "10 Min",
    "servings": 4
}

### Change a meal by meal name
PUT http://localhost:3000/meals/Chicken%20Ceasar%20Salad HTTP/1.1
content-type: application/json

{
    "calories": 250,
    "cookTemp": "Med High",
    "cookTime": "15 Min",
    "directions": "dsfsdffr",
    "ingredientAmounts": ["2", "4", "1/2", "1"],
    "ingredientUnits": ["Cup", "Cup", "Cup", "Cup"],
    "ingredients": ["Chicken Breast", "Romaine Lettuce", "Shredded Parmesan Cheese", "Croutons"],
    "mealName": "Chicken Ceasar Salad",
    "prepTime": "10 Min",
    "servings": 4
}

### Delete a meal by name
DELETE http://localhost:3000/meals/Chicken%20Ceasar%20Salad HTTP/1.1

### Get all users
GET http://localhost:3000/users HTTP/1.1

### Get One User
GET http://localhost:3000/users/yoyo HTTP/1.1

### Post a new user
POST http://localhost:3000/users HTTP/1.1
content-type: application/json

{
    "email": "dasda",
    "password": "nuF45!mber"
}

### Change a user by email
PUT http://localhost:3000/users/sone HTTP/1.1
content-type: application/json

{
    "email": "sonsdfe",
    "password": "nuD34!her"
}

### Delete a user by email
DELETE http://localhost:3000/users/num HTTP/1.1


### Render requests ###

### Render get all meals
GET https://lesson7.onrender.com/meals HTTP/1.1

### Render get one meal
GET https://lesson7.onrender.com/meals/Chicken%20Pizza HTTP/1.1

### Render post new meal
POST https://lesson7.onrender.com/meals HTTP/1.1
content-type: application/json

{
    "calories": 250,
    "cookTemp": "Med High",
    "cookTime": "15 Min",
    "directions": "Cook chicken. Cut chicken. Place on salad.",
    "ingredientAmounts": ["2", "4", "1/2", "1"],
    "ingredientUnits": ["Cup", "Cup", "Cup", "Cup"],
    "ingredients": ["Chicken Breast", "Romaine Lettuce", "Shredded Parmesan Cheese", "Croutons"],
    "mealName": "Chicken Ceasar Salad",
    "prepTime": "10 Min",
    "servings": 4
}

### Render put a meal by mealname
PUT https://lesson7.onrender.com/meals/Chicken%20Ceasar%20Salad HTTP/1.1
content-type: application/json

{
    "calories": 250,
    "cookTemp": "Med High",
    "cookTime": "15 Min",
    "directions": "ffffffffffff",
    "ingredientAmounts": ["2", "4", "1/2", "1"],
    "ingredientUnits": ["Cup", "Cup", "Cup", "Cup"],
    "ingredients": ["Chicken Breast", "Romaine Lettuce", "Shredded Parmesan Cheese", "Croutons"],
    "mealName": "Chicken Ceasar Salad",
    "prepTime": "10 Min",
    "servings": 4
}

### Render Delete a meal by mealname
DELETE https://lesson7.onrender.com/meals/Chicken%20Ceasar%20Salad HTTP/1.1

### Render get all users
GET https://lesson7.onrender.com/users HTTP/1.1

### Render get One User
GET https://lesson7.onrender.com/users/dasda HTTP/1.1

### Render post a new user
POST https://lesson7.onrender.com/users HTTP/1.1
content-type: application/json

{
    "email": "kendra.mae.anderson@gmail.com",
    "password": "MexicanF00d!"
}

### Render put a user by email
PUT https://lesson7.onrender.com/users/yoyo HTTP/1.1
content-type: application/json

{
    "email": "yoyo",
    "password": "numsdf%5Gdfber"
}

### Render delete a user by email
DELETE https://lesson7.onrender.com/users/yoyo HTTP/1.1